### ISSUE TITLE
Include Internet check 

### ISSUE THREAD

**Issue by ralphys** [linuxlite/liteupgrade#3]
The app asks the user to make sure it is connected to the internet before upgrading but it doesn't check whether that's true or not. 

Propose:
1- Initial internet check on script execution
2- Exit out with a dialog letting the user it cannot run because the computer is not connected to the internet.
3- Update dialogs sizes and info as needed

**Comment by linuxlite** [comment]
Logical and sensible. Please proceed.

**Comment by linuxlite** [comment]
Proposals 1 & 2 included.
